services:
  - type: web
    name: telegram-finance-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_bot_stable.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: PORT
        value: 10000
