services:
  - type: web
    name: telegram-finance-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python render_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: ADMIN_ID_2
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: ETHERSCAN_TOKEN
        sync: false
      - key: SOLSCAN_TOKEN
        sync: false
    healthCheckPath: /health
    autoDeploy: true
    deploy:
      strategy: immediate
